// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvhikoiuitamanctzfgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2aGlrb2l1aXRhbWFuY3R6Zmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTQwNzksImV4cCI6MjA3MDU5MDA3OX0.1Bo6dNMItzwzXLE0z46mdMsVUTBahiZhwUWLnmGTWiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});